# These are supported funding model platforms

# GitHub Sponsors
# github: [username]

# Open Collective
# open_collective: your-project

# Ko-fi
# ko_fi: username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Otechie
# otechie: username

# LFX Crowdfunding
# lfx_crowdfunding: project-name

# Custom URL
# custom: ['https://www.paypal.me/username', 'https://buy.stripe.com/test_xxxxx']

# Uncomment and add your sponsorship links above
# To enable GitHub Sponsors button in your repository
