name: Question
description: Ask a question about the course
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'm wondering about...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background
      placeholder: I was working on step X when...

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What have you already tried to find the answer?
      placeholder: I looked at...
